"""confirmation not null

Revision ID: 526bc969d966
Revises: 6a39326ae0f9
Create Date: 2018-04-21 16:23:35.049352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526bc969d966'
down_revision = '6a39326ae0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
